[pytest]
testpaths = tests
pythonpath = .
filterwarnings =
    ignore:Using `httpx` with `starlette.testclient` is deprecated.*:UserWarning
    ignore:The anyio\.abc\.BlockingPortal alias is deprecated.*:DeprecationWarning
